spring:
  application:
    name: ${APPLICATION_NAME:gateway}
  cloud:
    gateway:
      mvc:
        routes:
          - id: address
            uri: lb://ADDRESS
            predicates:
              - Path=/address/**
          - id: manager
            uri: lb://MANAGER
            predicates:
              - Path=/manager/**
  config:
    activate:
      on-profile: dev

server:
  port: ${APPLICATION_PORT:8080}
  compression:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: true
    secure-port-enabled: false
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: false

#Actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false