spring:
  application:
    name: ${APPLICATION_NAME:Address}
  datasource:
    driver-class-name: org.h2.Driver
    url:  "jdbc:h2:mem:wastemanager;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile: dev
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: true
    secure-port-enabled: false
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: false
server:
  port: ${APPLICATION_PORT:8081}
