spring:
  application:
    name: ${APPLICATION_NAME:gateway}
  cloud:
    gateway:
      mvc:
        routes:
        - id: address
          uri: lb://ADDRESS
          predicates:
            - Path=/address/**
          filters:
            - StripPrefix=1
        - id: manager
          uri: lb://MANAGER
          predicates:
            - Path=/manager/**
          filters:
            - StripPrefix=1
    config:
      enabled: false
  config:
    activate:
      on-profile: test

server:
  port: ${APPLICATION_PORT:8080}
  compression:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: true
    secure-port-enabled: false
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

#Actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
---
spring:
  application:
    name: ${APPLICATION_NAME:gateway}
  config:
    import: "configserver:${CONFIG_URL:http://localhost:8084}"
    activate:
      on-profile: dev
