spring:
  application:
    name: ${APPLICATION_NAME:gateway}
  cloud:
    gateway:
      mvc:
        routes:
        - id: address
          uri: lb://ADDRESS
          predicates:
            - Path=/address/**


server:
  port: ${APPLICATION_PORT:8080}
  compression:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

#Actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false