version: '3.8'

networks:
  my-app-net:

services:
  discovery:
    image: wastemanager.registry.azure.io/microservice/discovery:latest
    networks:
      - my-app-net
    ports:
      - "8761:8761"

  config:
    image: wastemanager.registry.azure.io/microservice/config:latest
    networks:
      - my-app-net
    environment:
      LOCAL_REPO_PATH: "/home/config"
      DISCOVERY_URL: "http://discovery:8761/eureka"
    volumes:
      - ./config:/home/config
    depends_on:
      - discovery
    ports:
      - "8084:8084"

  gateway:
    image: wastemanager.registry.azure.io/microservice/gateway:latest
    restart: always
    networks:
      - my-app-net
    environment:
      DISCOVERY_URL: "http://discovery:8761/eureka"
      CONFIG_URL: "http://config:8084/"
    ports:
      - "8080:8080"
    depends_on:
      - config


  address:
    image: wastemanager.registry.azure.io/microservice/address:latest
    restart: always
    networks:
      - my-app-net
    environment:
      DISCOVERY_URL: "http://discovery:8761/eureka"
      CONFIG_URL: "http://config:8084/"
    ports:
      - "8082:8082"
    depends_on:
      - gateway

  manager:
    image: wastemanager.registry.azure.io/microservice/manager:latest
    restart: always
    networks:
      - my-app-net
    environment:
      DISCOVERY_URL: "http://discovery:8761/eureka"
      CONFIG_URL: "http://config:8084/"
    ports:
      - "8081:8081"
    depends_on:
      - address
