spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      enabled: false
  application:
    name: ${APPLICATION_NAME:manager}
  datasource:
    driver-class-name: org.h2.Driver
    url:  ${CONNECTION_STRING:jdbc:h2:mem:wastemanager;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USER:sa}
    password: ${DB_PASS:sa}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
server:
  port: ${APPLICATION_PORT:8081}
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: true
    secure-port-enabled: false
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
address:
  name: ${WASTE_ADDRESS_SERVICE_NAME:address}
manager:
  center:
    kind: ${CENTER_AUTHORIZATION_KIND:WasteCenterAuthorization}
  manager:
    kind: ${MANAGER_KIND:WasteManager}
discovery:
  gateway: ${GATEWAY_SERVICE:GATEWAY}      
springdoc:
  version: 2.5.0
logging:
  level:
    web: info
