spring:
  application:
    name: ${APPLICATION_NAME:discovery}
  config:
    activate:
      on-profile: dev

server:
  port: ${APPLICATION_PORT:8761}
  compression:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


#Actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF